# Generated by Django 4.1.2 on 2022-10-14 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionNumber', models.IntegerField(unique=True)),
                ('question', models.TextField()),
                ('allowedtime', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MultipleAnswers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option1', models.TextField()),
                ('option2', models.TextField()),
                ('option3', models.TextField()),
                ('option4', models.TextField()),
                ('answer', models.CharField(choices=[('option1', 'option1'), ('option2', 'option2'), ('option3', 'option3'), ('option4', 'option4')], default='option3', max_length=200)),
                ('questionsId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizApp.questions')),
            ],
        ),
    ]
