# Generated by Django 4.1.2 on 2022-10-14 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multipleanswers',
            name='answer',
            field=models.CharField(choices=[('option1', 'option1'), ('option2', 'option2'), ('option3', 'option3'), ('option4', 'option4')], max_length=200),
        ),
        migrations.AlterField(
            model_name='multipleanswers',
            name='questionsId',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='quizApp.questions'),
        ),
    ]
